


#ifndef IDD_QUICK_SEEK_PANEL_RC_H
#define IDD_QUICK_SEEK_PANEL_RC_H

#define	IDD_QUICK_SEEK_PANEL		3600
#define	IDC_QUICK_SEEK_LIST                (IDD_QUICK_SEEK_PANEL + 1)
#define	IDC_QUICK_SEEK_LIST_AUX            (IDD_QUICK_SEEK_PANEL + 2)
#define	IDC_SEARCHFIELD_QUICKSEEK          (IDD_QUICK_SEEK_PANEL + 3)
#define	IDC_RELOADBUTTON_QUICKSEEK         (IDD_QUICK_SEEK_PANEL + 4)
#define	IDC_SORTBUTTON_QUICKSEEK           (IDD_QUICK_SEEK_PANEL + 5)

#endif //IDD_QUICK_SEEK_PANEL_RC_H

